# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.2.dev1709221830
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(708, 531)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labPic = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labPic.sizePolicy().hasHeightForWidth())
        self.labPic.setSizePolicy(sizePolicy)
        self.labPic.setText(_fromUtf8(""))
        self.labPic.setObjectName(_fromUtf8("labPic"))
        self.verticalLayout_5.addWidget(self.labPic)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_6 = QtGui.QWidget(self.centralWidget)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.widget_7 = QtGui.QWidget(self.widget_6)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnTakePic = QtGui.QPushButton(self.widget_7)
        self.btnTakePic.setObjectName(_fromUtf8("btnTakePic"))
        self.verticalLayout_2.addWidget(self.btnTakePic)
        self.btnAutofocus = QtGui.QPushButton(self.widget_7)
        self.btnAutofocus.setObjectName(_fromUtf8("btnAutofocus"))
        self.verticalLayout_2.addWidget(self.btnAutofocus)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.widget_8 = QtGui.QWidget(self.widget_6)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnMoveUp = QtGui.QPushButton(self.widget_8)
        self.btnMoveUp.setObjectName(_fromUtf8("btnMoveUp"))
        self.verticalLayout_3.addWidget(self.btnMoveUp)
        self.btnMoveDown = QtGui.QPushButton(self.widget_8)
        self.btnMoveDown.setObjectName(_fromUtf8("btnMoveDown"))
        self.verticalLayout_3.addWidget(self.btnMoveDown)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.widget_2 = QtGui.QWidget(self.widget_6)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_9 = QtGui.QWidget(self.widget_2)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.formLayout = QtGui.QFormLayout(self.widget_9)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labInterval = QtGui.QLabel(self.widget_9)
        self.labInterval.setObjectName(_fromUtf8("labInterval"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labInterval)
        self.spinInterval = QtGui.QSpinBox(self.widget_9)
        self.spinInterval.setMaximum(99999)
        self.spinInterval.setObjectName(_fromUtf8("spinInterval"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinInterval)
        self.labTime = QtGui.QLabel(self.widget_9)
        self.labTime.setObjectName(_fromUtf8("labTime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labTime)
        self.spinTime = QtGui.QSpinBox(self.widget_9)
        self.spinTime.setMaximum(99999)
        self.spinTime.setObjectName(_fromUtf8("spinTime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinTime)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.btnStart = QtGui.QPushButton(self.widget_2)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.verticalLayout_4.addWidget(self.btnStart)
        self.btnStop = QtGui.QPushButton(self.widget_2)
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.verticalLayout_4.addWidget(self.btnStop)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 708, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btnTakePic.setText(_translate("MainWindow", "Take Picture", None))
        self.btnAutofocus.setText(_translate("MainWindow", "Autofocus", None))
        self.btnMoveUp.setText(_translate("MainWindow", "Move Up", None))
        self.btnMoveDown.setText(_translate("MainWindow", "Move Down", None))
        self.labInterval.setText(_translate("MainWindow", "Set Interval", None))
        self.labTime.setText(_translate("MainWindow", "Set Time", None))
        self.btnStart.setText(_translate("MainWindow", "Start", None))
        self.btnStop.setText(_translate("MainWindow", "Stop", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

